version: 0.2

env:
  variables:
    ENVIRONMENT: dev  # Set your environment variables here

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - cd src/ut_anagramma 
      - python3 -m venv venv  # Create a virtual environment
      - . venv/bin/activate  # Activate the virtual environment
      - pip install wheel setuptools>=61.0
      - pip install -r requirements.txt  # Install dependencies

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Running tests...
      - cd src/ut_anagramma
      - . venv/bin/activate  # Ensure the virtual environment is activated
      #- pip install pytest  # Ensure pytest is installed
      #- pytest  # Run your tests

artifacts:
  files:
    - '**/*'  # Specify the files to include in the build artifacts
  base-directory: .  # Base directory for artifacts
