runtime: python37

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
